<?php
namespace Remote\Models;

// Placeholder to avoid parse errors from autogenerated remote model stubs.
// If you need specific remote model classes, recreate them intentionally.

class RemoteModelsPlaceholder {
    // intentionally empty
}
